version: '3'

services:
  database:
    image: postgres:16.0-alpine3.18
    container_name: 'database'
    ports:
      - '5432:5432'
    env_file:
      - .env
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
  backend:
    container_name: 'backend'
    build: app/
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - static_volume:/app/static
  frontend:
    image: node:20.8-alpine
    container_name: 'frontend'
    depends_on:
      - backend
    ports:
      - "80:5173"

volumes:
  static_volume: