version: '3'

services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - db_volume:/var/lib/postgresql/data
  backend:
    container_name: backend
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "alembic revision --autogenerate -m "creation" && alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - static_volume:/app/static
#  frontend:
#    image: node:20.8-alpine
#    container_name: 'frontend'
#    depends_on:
#      - backend
#    ports:
#      - "80:5173"

volumes:
  static_volume:
#  db_volume: