"""empty message

Revision ID: abad282e8bc1
Revises: 4153a92a5816
Create Date: 2023-10-15 15:56:15.174565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abad282e8bc1'
down_revision: Union[str, None] = '4153a92a5816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('name', sa.String(), nullable=False))
    op.add_column('file', sa.Column('info', sa.String(length=16), nullable=False))
    op.add_column('file', sa.Column('number', sa.Integer(), nullable=True))
    op.drop_column('file', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('file', 'number')
    op.drop_column('file', 'info')
    op.drop_column('file', 'name')
    # ### end Alembic commands ###
