"""empty message

Revision ID: b7ceabbda7d3
Revises: abad282e8bc1
Create Date: 2023-10-17 11:29:23.831882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7ceabbda7d3'
down_revision: Union[str, None] = 'abad282e8bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('bfile', postgresql.BYTEA(), nullable=True))
    op.drop_column('file', 'name')
    op.drop_column('file', 'info')
    op.drop_column('file', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('info', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('file', 'bfile')
    # ### end Alembic commands ###
