"""empty message

Revision ID: 3324427f464e
Revises: de49772fb73f
Create Date: 2023-10-15 11:23:21.010914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '3324427f464e'
down_revision: Union[str, None] = 'de49772fb73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'expansion')
    op.drop_column('file', 'size')
    op.drop_column('file', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('size', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('expansion', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
